---
title: "julia_stm"
author: "Peter Hahn"
date: "11 11 2018"
output: html_document
---
#Links
[https://github.com/dondealban/learning-stm#workflow]

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE, message=FALSE, fig.width = 12, fig.height = 8)
## load libraries
library(tidyverse)
#library(RISmed)
library(wordcloud)
library(stringr)
library(igraph)
#library(ggraph)
#library(tidygraph)
library(tm)
library(tidytext)
#library(widyr)
library(topicmodels)
library(furrr)
library(stm)
```

## LOad file
```{r}
abstr_dtm <- load("doc_term.RData")
```

### calculate stm

```{r}
plan(multiprocess)

many_models <- data_frame(K = c(20,30,40,50,60,70)) %>%
  mutate(topic_model = future_map(K, ~stm(abstr_sparse, K = .,
                                          verbose = FALSE)))
```

## evaluate

```{r}
        heldout <- make.heldout(abstr_sparse)

k_result <- many_models %>%
  mutate(exclusivity = map(topic_model, exclusivity),
         semantic_coherence = map(topic_model, semanticCoherence, abstr_sparse),
         eval_heldout = map(topic_model, eval.heldout, heldout$missing),
         residual = map(topic_model, checkResiduals, abstr_sparse),
         bound =  map_dbl(topic_model, function(x) max(x$convergence$bound)),
         lfact = map_dbl(topic_model, function(x) lfactorial(x$settings$dim$K)),
         lbound = bound + lfact,
         iterations = map_dbl(topic_model, function(x) length(x$convergence$bound)))

k_result
```

# plot

```{r}
        k_result %>%
  transmute(K,
            `Lower bound` = lbound,
            Residuals = map_dbl(residual, "dispersion"),
            `Semantic coherence` = map_dbl(semantic_coherence, mean),
            `Held-out likelihood` = map_dbl(eval_heldout, "expected.heldout")) %>%
  gather(Metric, Value, -K) %>%
  ggplot(aes(K, Value, color = Metric)) +
  geom_line(size = 1.5, alpha = 0.7, show.legend = FALSE) +
  facet_wrap(~Metric, scales = "free_y") +
  labs(x = "K (number of topics)",
       y = NULL,
       title = "Model diagnostics by number of topics",
       subtitle = "These diagnostics indicate that a good number of topics would be around 24")
```

## final model with k = 24

```{r}
topic_model <- stm(abstr_sparse, K = 30, 
                   verbose = FALSE, init.type = "Spectral")

## alternative

```

```{r}
        ##save if necessary or load
        # save(topic_model,file="topic_60.RData")
        tidy_stm <- tidy(topic_model)
```
## top terms

```{r}
        top_terms <- tidy_stm %>% 
        group_by(topic) %>%
        filter(!is.na(term)) %>% 
        top_n(10,beta) %>% 
        ungroup() %>% 
        arrange(topic,-beta)
        
```

### Graphical representation of top terms
12 topics were bulid for the abstracts. After test of 6,8,10,16,24 topics best results are achieved with 12 topics.
For each topic the top 10 terms representing the topic are presented.
```{r include=TRUE}
        top_terms %>% 
  mutate(term = reorder(term, beta)) %>%
  group_by(topic, term) %>%    
  arrange(desc(beta)) %>%  
  ungroup() %>%
  mutate(term = factor(paste(term, topic, sep = "__"), 
                       levels = rev(paste(term, topic, sep = "__")))) %>%
  ggplot(aes(term, beta, fill = as.factor(topic))) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  scale_x_discrete(labels = function(x) gsub("__.+$", "", x)) +
  labs(title = "Top 10 terms in each LDA topic",
       x = NULL, y = expression(beta)) +
  facet_wrap(~ topic, ncol = 6, scales = "free")

```

## gamma
```{r}
        lda_gamma <- tidy(topic_model,matrix="gamma",document_names = abstr_sparse[])
## join with abstracts   

        joined <- left_join(gamma,abstracts,by=c("document"="DOI"))

        top_gamma <- lda_gamma %>% group_by(document) %>% arrange(desc(gamma)) %>% top_n(2,gamma) %>% arrange(desc(document))
        
# plot topic by year
        joined %>% group_by(year,topic) %>% count() %>% 
                ggplot(aes(year,n))+geom_point()+facet_wrap(~topic)
        
```

### join papers and gamma values

```{r}
yy <- abstracts %>% filter(DOI==10050243)  ## number == document in topic_model
```

