---
title: "stm_part"
author: "Peter Hahn"
date: "1 12 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
plan(multiprocess)

many_models <- data_frame(K = c(20,30,40,50,60,70)) %>%
  mutate(topic_model = future_map(K, ~stm(abstr_sparse, K = .,
                                          verbose = FALSE)))
```

## evaluate

```{r}
        heldout <- make.heldout(abstr_sparse)

k_result <- many_models %>%
  mutate(exclusivity = map(topic_model, exclusivity),
         semantic_coherence = map(topic_model, semanticCoherence, abstr_sparse),
         eval_heldout = map(topic_model, eval.heldout, heldout$missing),
         residual = map(topic_model, checkResiduals, abstr_sparse),
         bound =  map_dbl(topic_model, function(x) max(x$convergence$bound)),
         lfact = map_dbl(topic_model, function(x) lfactorial(x$settings$dim$K)),
         lbound = bound + lfact,
         iterations = map_dbl(topic_model, function(x) length(x$convergence$bound)))

k_result
```

# plot

```{r}
        k_result %>%
  transmute(K,
            `Lower bound` = lbound,
            Residuals = map_dbl(residual, "dispersion"),
            `Semantic coherence` = map_dbl(semantic_coherence, mean),
            `Held-out likelihood` = map_dbl(eval_heldout, "expected.heldout")) %>%
  gather(Metric, Value, -K) %>%
  ggplot(aes(K, Value, color = Metric)) +
  geom_line(size = 1.5, alpha = 0.7, show.legend = FALSE) +
  facet_wrap(~Metric, scales = "free_y") +
  labs(x = "K (number of topics)",
       y = NULL,
       title = "Model diagnostics by number of topics",
       subtitle = "These diagnostics indicate that a good number of topics would be around 60")
```

## make final model after evaluation with k = 60

```{r}
topic_model <- stm(abstr_sparse, K = 30, 
                   verbose = FALSE, init.type = "Spectral")
```

```{r}
        ##save if necessary or load
        # save(topic_model,file="topic_35.RData")
         tidy_stm <- tidy(topic_model)
```